LINUXDROID_PKG_MAINTAINER="Leonid Plyushch <leonid.plyushch@gmail.com> @xeffyr"

LINUXDROID_PKG_HOMEPAGE=https://xorg.freedesktop.org/
LINUXDROID_PKG_DESCRIPTION="X.Org X11 Protocol headers"
LINUXDROID_PKG_VERSION=2018.4
LINUXDROID_PKG_REVISION=4
LINUXDROID_PKG_SRCURL=https://xorg.freedesktop.org/archive/individual/proto/xorgproto-${LINUXDROID_PKG_VERSION}.tar.bz2
LINUXDROID_PKG_SHA256=fee885e0512899ea5280c593fdb2735beb1693ad170c22ebcc844470eec415a0
LINUXDROID_PKG_DEPENDS="xorg-util-macros"
LINUXDROID_PKG_CONFLICTS="x11-proto"
LINUXDROID_PKG_REPLACES="x11-proto"
LINUXDROID_PKG_NO_DEVELSPLIT=true
LINUXDROID_PKG_PLATFORM_INDEPENDENT=true
LINUXDROID_PKG_BUILD_IN_SRC=true
