LINUXDROID_PKG_MAINTAINER="Leonid Plyushch <leonid.plyushch@gmail.com> @xeffyr"

LINUXDROID_PKG_HOMEPAGE=https://xorg.freedesktop.org/
LINUXDROID_PKG_DESCRIPTION="X11 authorisation library"
LINUXDROID_PKG_VERSION=1.0.8
LINUXDROID_PKG_REVISION=6
LINUXDROID_PKG_SRCURL=https://xorg.freedesktop.org/releases/individual/lib/libXau-${LINUXDROID_PKG_VERSION}.tar.bz2
LINUXDROID_PKG_SHA256=fdd477320aeb5cdd67272838722d6b7d544887dfe7de46e1e7cc0c27c2bea4f2
LINUXDROID_PKG_BUILD_DEPENDS="xorgproto"
LINUXDROID_PKG_DEVPACKAGE_DEPENDS="xorgproto"
