LINUXDROID_PKG_MAINTAINER="Leonid Plyushch <leonid.plyushch@gmail.com> @xeffyr"

LINUXDROID_PKG_HOMEPAGE=https://xcb.freedesktop.org/
LINUXDROID_PKG_DESCRIPTION="Utility libraries for XC Binding"
LINUXDROID_PKG_VERSION=0.4.0
LINUXDROID_PKG_REVISION=4
LINUXDROID_PKG_SRCURL=https://xcb.freedesktop.org/dist/xcb-util-${LINUXDROID_PKG_VERSION}.tar.gz
LINUXDROID_PKG_SHA256=0ed0934e2ef4ddff53fcc70fc64fb16fe766cd41ee00330312e20a985fd927a7
LINUXDROID_PKG_DEPENDS="libxcb"
LINUXDROID_PKG_BUILD_DEPENDS="xorg-util-macros"
