LINUXDROID_PKG_MAINTAINER="Leonid Plyushch <leonid.plyushch@gmail.com> @xeffyr"

LINUXDROID_PKG_HOMEPAGE=https://xcb.freedesktop.org/
LINUXDROID_PKG_DESCRIPTION="XML-XCB protocol descriptions"
LINUXDROID_PKG_VERSION=1.13
LINUXDROID_PKG_REVISION=4
LINUXDROID_PKG_SRCURL=https://xcb.freedesktop.org/dist/xcb-proto-${LINUXDROID_PKG_VERSION}.tar.bz2
LINUXDROID_PKG_SHA256=7b98721e669be80284e9bbfeab02d2d0d54cd11172b72271e47a2fe875e2bde1
LINUXDROID_PKG_PLATFORM_INDEPENDENT=true
LINUXDROID_PKG_CONFLICTS="xcbproto"
LINUXDROID_PKG_REPLACES="xcbproto"
